# Site settings ------------------------------------

title: Hannah Boneham
email: hannah-boneham@domain.com
description: # this means to ignore newlines until "baseurl:"
  The average working person in Britain will spend over 90,000 hours of their lives at work.
  When you reflect back on your career, how many of those hours do you think you will remember fondly?
  Our leaders have a significant ability to support our wellbeing at work but their success relies on understanding how their efforts are perceived by those who work for them.

# twitter_username: jekyllrb

# baseurl: '' # the subpath of your site, e.g. /blog/
# url: 'http://yourdomain.com' # the base hostname & protocol for your site

# this base url would be right if just on Github pages, breaks when connected to domain.
# baseurl: "/apathofbravery"

# For manual FTP upload
# baseurl: ""
# url: "apathofbravery.com"
# then, jekyll serve in terminal, then copy _site folder

# use...
# jekyll serve --config _config.yml,_config_dev.yml 
# ... in terminal to work on local _config_dev.yml for baseurl + url

# Setup for Github Pages deployment
# baseurl: "/hannah-boneham"
baseurl: ""
# url: 'https://keeftango.github.io'

# Setup for Github pages with own domain URL
# baseurl: ""
# url: 'http://website.com'

# Build settings ------------------------------------

sass:
  sass_dir: _src/css