# Site settings ------------------------------------

title: Hannah Boneham
email: hannah-boneham@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# twitter_username: jekyllrb

# baseurl: '' # the subpath of your site, e.g. /blog/
# url: 'http://yourdomain.com' # the base hostname & protocol for your site

# this base url would be right if just on Github pages, breaks when connected to domain.
# baseurl: "/apathofbravery"

# For manual FTP upload
# baseurl: ""
# url: "apathofbravery.com"
# then, jekyll serve in terminal, then copy _site folder

# use...
# jekyll serve --config _config.yml,_config_dev.yml 
# ... in terminal to work on local _config_dev.yml for baseurl + url

# Setup for Github Pages deployment
baseurl: '/hannah-boneham'
url: 'https://keeftango.github.io'

# Setup for Github pages with own domain URL
# baseurl: ""
# url: 'http://website.com'

# Build settings ------------------------------------

sass:
  sass_dir: _src/css